### PR TITLE
tag project to v2.0.0

### PR DESCRIPTION
**Pull request by sjpadgett**
bump project version to 2.0.0

### CODE REVIEW

**Comment by kchapple** [comment]
@sjpadgett we need to update the oe-cqm-parsers dependency in this repo too, so openemr has the right value sets. Needs a new version, then put the new version string in this repo’s package.json.

**Comment by sjpadgett** [comment]
We've already used v5.5.0 on  oe-cqm-parser and current is 5.6.0 so don't think we can't us the qdm version for our versioning so i'm going to call parser version to follow openemr major 6.0.0. Or can I delete existing tags and tag the current as 5.5.0? Do you know?

**Comment by kchapple** [comment]
It shouldn’t be a problem to delete tags and versions since we’re the only ones using this right now.

**Comment by kchapple** [comment]
It doesn’t need to be related to qdm version, 6.0 would be fine as well

**Comment by sjpadgett** [comment]
Yes parser is a published package where can't do that so this 6.0.0 will be it thanks

**Pull request merged**
